### ISSUE TITLE
Handle Gurobi Environments

### ISSUE THREAD

**Issue by peno64** [Gurobi/gurobi-modelanalyzer#3]
With following python file:

```python
import sys
import gurobipy as gp
import gurobi_modelanalyzer as ma
m=gp.read(sys.argv[1])
m.optimize()
print('kappa_explain1')
ma.kappa_explain(m)
print('kappa_explain2')
ma.kappa_explain(m, expltype="COLS")
print('angle_explain')
ma.angle_explain(m)
```

With attached file:
[oops1.mps.txt](https://github.com/Gurobi/gurobi-modelanalyzer/files/13256693/oops1.mps.txt)

I get the following error:

```
...
Solved in 0 iterations and 0.00 seconds (0.00 work units)
Optimal objective  1.000000000e+00
Vector matrix product of certificate of ill conditioning and basis:
ZTHREE
Traceback (most recent call last):
  File "D:\brol\modelanalyzer.py", line 7, in <module>
    ma.kappa_explain(m)
  File "C:\Users\peno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gurobi_modelanalyzer\results_analyzer.py", line 421, in kappa_explain
    refine_output(resmodel, yvaldict, expltype, submatrix)
  File "C:\Users\peno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gurobi_modelanalyzer\results_analyzer.py", line 1640, in refine_output
    contoadd = condict[conname]
               ~~~~~~~^^^^^^^^^
KeyError: '(mult=1.0)MYEQN'
...
```

Note that I run this on a windows 11 computer with the latest version of this tool (I did a pip install today)
The gurobi version is 10.0.3 (running on a compute server)
The python version is: 3.11.6

I get this error for almost all my models I test.

**Comment by mattmilten** [comment]
This is an issue with model handling in Compute Server environments. The code is not yet compatible with Gurobi Compute Server.

Thanks for bringing this up!

**Comment by amakarowsky** [comment]
Hi @torressa , @mattmilten - just wanted to add that the environment defaulting is also a blocker for users which license through an ISV key.

Replacing calls to gp.model(.) with gp.Model(.,env) worked for me. I fed in env through an optional argument to kappa_explain. Some top level setEnvironment is probably cleaner. @peno64 you may want to try this.

**Comment by venaturum** [comment]
Looks like an env argument is not enough to resolve the issue with compute servers.

The code uses Model.copy() in a couple of places which [will not work with compute server environments](https://docs.gurobi.com/projects/optimizer/en/current/reference/python/model.html#Model.copy).

I have a workaround which I'll submit as a PR for review.

**Comment by venaturum** [comment]
#internal
related: GH9676

**Comment by amakarowsky** [comment]
Many thanks @venaturum . I can't speak for the computer server issue, but my testing of your changes confirms passing environments through kappa_explain resolves my licensing issue.
